### ISSUE TITLE
hardware parameters in the large K8s cluster

### ISSUE THREAD

**Issue by Forest-L** [kubesphere/community#135]
* Kubelet parameters
```
maxPods: 110
rotateCertificates: true
kubeReserved:
  cpu: 200m
  memory: 250Mi
systemReserved:
  cpu: 200m
  memory: 250Mi
evictionHard:
  memory.available: 5%
evictionSoft:
  memory.available: 10%
evictionSoftGracePeriod: 
  memory.available: 2m
evictionMaxPodGracePeriod: 120
evictionPressureTransitionPeriod: 30s
```

* Etcd parameters, refer to [etcd](https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/hardware.md)
![image](https://user-images.githubusercontent.com/50984129/90220313-8b9ccd00-de3a-11ea-8167-326b1c6cf0ac.png)
