### ISSUE TITLE
How to generate DevOps kubeconfig on AWS

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/community#165]
1. create ServiceAccount

devops-deploy.yaml , take the namespace kubesphere-sample-dev as an example.

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-deploy
  namespace: kubesphere-sample-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devops-deploy-role
  namespace: kubesphere-sample-dev
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devops-deploy-rolebinding
  namespace: kubesphere-sample-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: devops-deploy-role
subjects:
- kind: ServiceAccount
  name: devops-deploy
  namespace: kubesphere-sample-dev
```

```bash
kubectl apply -f devops-deploy.yaml
```

2. Get Service Account Token

```bash
export TOKEN_NAME=$(kubectl -n kubesphere-sample-dev get sa devops-deploy -o jsonpath='{.secrets[0].name}')
kubectl -n kubesphere-sample-dev get secret "${TOKEN_NAME}" -o jsonpath='{.data.token}' | base64 -d

xxxxxxxx...
```

3. Replace kubeconfig on Web

![image](https://user-images.githubusercontent.com/43693241/92102217-e5c4f880-ee10-11ea-8fb5-52176558eab1.png)

This kubecofig is incorrect. You should replace 

```
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FUR...
    client-key-data: LS0tLS1CRUdJTiBQUk...
```

by

```
  user:
    token: xxxxxxxx...
```

4. Enjoy DevOps Deploy

![image](https://user-images.githubusercontent.com/43693241/92102592-62f06d80-ee11-11ea-8f96-ae4026dba070.png)
